language: ruby
install:
  - sudo apt-get update && sudo apt-get install debconf-utils
  - echo "firebird2.5-super       shared/firebird/sysdba_password/new_password    password        masterkey" | sudo debconf-set-selections
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev firebird-dev firebird2.5-super
  - gem install rake --no-ri --no-rdoc -v 10.5.0
before_script:
  - sudo service firebird2.5-super start
script:
  - bundle
  - bundle exec rake
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
